apiVersion: v1
kind: Secret
metadata:
  name: synapse-secrets
  namespace: synapse
type: Opaque
stringData:
  MONGODB_URI: "mongodb://chinmay:123456@mongodb:27017/synapse?authSource=admin"
  JWT_SECRET: "dev-secret-key-change-in-production"
