apiVersion: v1
kind: Service
metadata:
  name: synapse-backend
  namespace: synapse
spec:
  type: NodePort
  selector:
    app: synapse-backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-frontend
  namespace: synapse
spec:
  type: NodePort
  selector:
    app: synapse-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: synapse
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
